# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Clark-XM
subtitle: Stay Hungry, Stay Foolish # 副标题
description: 银河街角，时光路口 # 站点描述
keywords:
author: Clark-XM
language: zh-Hans # 语言设置
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://fighttogetter.win
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
# theme: yilia
theme: next

search: # 本地搜索插件
  path: search.xml
  field: post
  format: html
  limit: 10000

# feed: # RSS订阅插件
#   type: atom
#   path: atom.xml
#   limit: 0
# RSS订阅
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '

  # 搜索
# search:
#   path: search.xml
#   field: post
#   format: html
#   limit: 10000

plugins:
baidusitemap: # 百度站点地图
  path: baidusitemap.xml



# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  # repository: # 可选择同时部署到 GitHub 和 coding 或者只部署到 Github
    # github: git@github.com:garretming/garretming.github.io.git
    # coding: git@git.coding.net:你的Coding名/你的Coding名.git
  repository: git@github.com:garretming/garretming.github.io.git  #这里的网址填你自己的 repository:
  branch: master 
